version: '3'
services:
  db:
    image: mongo:latest
    container_name: mongo_db
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
  bot:
    build: .
    container_name: tesh_bot
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
      - NODE_ENV
      - DB_HOST
      - DISCORD_BOT_TOKEN
